### ISSUE TITLE
URLs with dots cause issues

### ISSUE THREAD

**Issue by mantoni** [brentertz/connect-pushstate#1]
Currently, `connect-pushstate` distinguishes static resources from other URLs by checking for the file extension. While this works in most cases, it causes issues when using a dot in a URL that is supposed to be handled by the application.

Some examples:

- `/version/1.2.3`
- `/user/my.name`
- `/actually-dynamically-created-in-the-browser.csv`

Would it be possible to add a regular expression that has to be matched in order to classify a URL as static and forward to `next()`? If the option is not provided, the current behavior can still be used as the default. Alternatively, a matcher function could be passed in as an option.

Any thoughts?

**Comment by brentertz** [comment]
Hello. This functionality should already supported via the 'allow' option, which accepts a regular expression and when matched will allow the request to pass through without being redirected.

**Comment by mantoni** [comment]
Yes, I saw the `allow` option. The conditional is `if (allowed || hasFileExtension) {` so even if I specify the allowed resources, anything that has a file extension is also not redirected. But I want it to be redirected.

**Comment by brentertz** [comment]
Can you please see if the following updates will suit your needs.

https://github.com/brentertz/connect-pushstate/tree/disallow

**Comment by brentertz** [comment]
Closing as the issue should be resolved via v1.1.0, which has also been published to npm.
